# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-16 02:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('replacement', '0002_auto_20170116_0154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Repuesto',
        ),
    ]
