# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-16 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replacement', '0004_repuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Repuesto'),
        ),
    ]
