# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 05:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Informacion de la Sucursal', 'verbose_name_plural': 'Informacion de las Sucursales'},
        ),
    ]
