# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-16 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motorcycle', '0001_initial'),
        ('replacement', '0005_repuesto_name'),
        ('usuario', '0003_usuario'),
        ('personal', '0002_auto_20170116_0346'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaMotocicleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha de Venta')),
                ('cantidad', models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Cantidad')),
                ('total', models.FloatField()),
                ('motocicleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorcycle.Motorcycle')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Personal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
            ],
            options={
                'verbose_name_plural': 'Venta de Motocicletas',
                'verbose_name': 'Venta de Motocicleta',
            },
        ),
        migrations.CreateModel(
            name='VentaRepuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha de Venta')),
                ('cantidad', models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Cantidad')),
                ('total', models.FloatField()),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Personal')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='replacement.Repuesto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
            ],
            options={
                'verbose_name_plural': 'Venta de Repuestos',
                'verbose_name': 'Venta de Repuesto',
            },
        ),
    ]
