# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventamotocicleta',
            name='cantidad',
            field=models.PositiveSmallIntegerField(default=1, null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='ventamotocicleta',
            name='total',
            field=models.FloatField(blank=True, null=True, verbose_name='Monto a pagar'),
        ),
        migrations.AlterField(
            model_name='ventarepuesto',
            name='cantidad',
            field=models.PositiveSmallIntegerField(default=1, null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='ventarepuesto',
            name='total',
            field=models.FloatField(blank=True, null=True, verbose_name='Monto a pagar'),
        ),
    ]
