# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-15 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_code', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Codigo Motocicleta')),
                ('stock', models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Cantidad')),
                ('brand', models.CharField(blank=True, default='USM', max_length=100, null=True, verbose_name='Marca')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Color')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Precio')),
                ('cylinder_capacity', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cilindrada')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('box', models.CharField(blank=True, max_length=100, null=True, verbose_name='Caja')),
                ('motor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Motor')),
                ('characteristics', models.TextField(blank=True, null=True, verbose_name='Caracteristicas')),
                ('image', models.ImageField(blank=True, null=True, upload_to='imagenes/motocicletas/%Y/%m/%d', verbose_name='Imagen')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorcycle.CreateType')),
            ],
            options={
                'verbose_name': 'Motocicleta',
                'verbose_name_plural': 'Motocicletas',
            },
        ),
    ]
