# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createtype',
            options={'verbose_name': 'Tipo de Motocicleta', 'verbose_name_plural': 'Tipos de motocicleta'},
        ),
        migrations.AlterField(
            model_name='createtype',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorcycle.CreateType', verbose_name='Tipo'),
        ),
    ]
