# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-15 22:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personal',
        ),
    ]
