# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-15 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0002_delete_personal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Cedula')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre')),
                ('paterno', models.CharField(blank=True, max_length=150, null=True, verbose_name='Paterno')),
                ('materno', models.CharField(blank=True, max_length=150, null=True, verbose_name='Materno')),
                ('celular', models.CharField(blank=True, max_length=50, null=True, verbose_name='Celular')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
                'verbose_name': 'Usuario',
            },
        ),
    ]
