# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-15 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Cedula')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre')),
                ('paterno', models.CharField(blank=True, max_length=150, null=True, verbose_name='Paterno')),
                ('materno', models.CharField(blank=True, max_length=150, null=True, verbose_name='Materno')),
                ('celular', models.CharField(blank=True, max_length=50, null=True, verbose_name='Celular')),
                ('cargo', models.CharField(choices=[('GERENTE', 'Gerente'), ('VENDEDOR', 'Vendedor'), ('SECRETARIA', 'Secretaria')], default='GERENTE', max_length=50, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
            },
        ),
    ]
