# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-16 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='cargo',
            field=models.CharField(choices=[('GERENTE', 'Gerente'), ('VENDEDOR', 'Vendedor'), ('SECRETARIA', 'Secretaria'), ('MECANICO', 'Mecanico')], default='GERENTE', max_length=50, verbose_name='Cargo'),
        ),
    ]
