# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-16 03:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
        ('motorcycle', '0001_initial'),
        ('usuario', '0003_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=50, unique=True, verbose_name='Placa Motocicleta')),
                ('detalle_reparacion', models.TextField(blank=True, null=True, verbose_name='Detalle de la reparacion')),
                ('inicio_reparacion', models.DateTimeField(verbose_name='Fecha de entrega al taller ')),
                ('fin_reparacion', models.DateTimeField(verbose_name='Fecha de Devolucion al usuario')),
                ('motocicleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorcycle.Motorcycle')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Personal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
            ],
            options={
                'verbose_name_plural': 'Reparacion de Motocicletas',
                'verbose_name': 'Reparacion de Motocicleta',
            },
        ),
    ]
