# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0003_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('GENERAL', 'Información General'), ('WEB', 'Plataforma Web'), ('MOBILE', 'Aplicación móvil'), ('SECURITY', 'Accesos'), ('PAYMENTS', 'Pagos'), ('ACCOUNTS', 'Cuentas'), ('SECURITY', 'Seguridad'), ('BOTS', 'Bots'), ('SUBSCRIPTIONS', 'Suscripciones')], default='GENERAL', max_length=50, verbose_name='Categoria')),
                ('question', models.TextField(verbose_name='Pregunta')),
                ('answer', models.TextField(verbose_name='Respuesta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario', verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150, verbose_name='Asunto')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('date', models.DateField(auto_now=True, verbose_name='Fecha de publicación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario', verbose_name='Usuario')),
            ],
        ),
    ]
